version: '3'
services:
    bank:
      container_name: bank-con
      build: ./mobile
      ports:
        - "5001:80"
    mobile:
      container_name: mobile-con
      build: ./bank
      ports:
        - "5002:80"
    nginx:
        build: ./nginx
        ports:
            - "8080:80"
        depends_on:
            - bank
            - mobile
